services:
  web:
    image: nginx:latest
    container_name: yii2_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yii2_network

  php:
    build:
      context: ./php
    container_name: yii2_php
    volumes:
      - ./src:/var/www/html
    networks:
      - yii2_network

  db:
    image: postgres:latest
    container_name: yii2_db
    environment:
      POSTGRES_USER: yii2user
      POSTGRES_PASSWORD: yii2password
      POSTGRES_DB: yii2db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - yii2_network

volumes:
  db_data:

networks:
  yii2_network:
